version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ZMQ_PORT=5555
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
